import {
  BEE_FLYING_ANIMATION,
  BEE_HIVE,
  BEE_NEST,
  BUTTERFLY,
  CHICKEN_01,
  CHICKEN_02,
  CHICKEN_03,
  CHICKEN_04,
  CHICKEN_05,
  CHICKEN_06,
  CHICKEN_07,
  CHICKEN_08,
  CHICKEN_09,
  CHICKEN_10,
  CHICKEN_11,
  CHICKEN_12,
  CHICKEN_13,
  CHICKEN_14,
  CHICKEN_15,
  CHICKEN_16,
  CHICKEN_17,
  CHICKEN_18,
  COW_01,
  COW_02,
  COW_03,
  COW_04,
  COW_05,
  COW_06,
  COW_07,
  COW_08,
  COW_09,
  HORSE_01,
  ALBINO_KAPYBARA_BUBBLES,
  ALBINO_KAPYBARA_DIVE,
  ALBINO_KAPYBARA_EMERGE,
  ALBINO_KAPYBARA_IDLE,
  ALBINO_KAPYBARA_LOOKAROUND,
  ALBINO_KAPYBARA_LOOKAROUND_SUBMERGED,
  KAPYBARA_BUBBLES,
  KAPYBARA_DIVE,
  KAPYBARA_EMERGE,
  KAPYBARA_IDLE,
  KAPYBARA_LOOKAROUND,
  KAPYBARA_LOOKAROUND_SUBMERGED,
  PIG_01,
  PIG_02,
  PIG_03,
  PIG_04,
  PIG_05,
  PIG_06,
  PIG_07,
  PIG_08,
  PIG_09,
  PIG_10,
  PIG_11,
  PIG_12,
  PIG_13,
  PIG_14,
  PIG_15,
  PIG_16,
  SHEEP_01,
  SHEEP_02,
  SHEEP_03,
  SHEEP_04,
  SHEEP_05,
  SHEEP_06,
  SHEEP_07,
  SHEEP_08,
  SHEEP_09,
  APPLE_TREE,
  BERRIES,
  CHERRY_TREE,
  CROPS,
  FRUIT_TREES_FRUIT_OBJECTS,
  FRUIT_TREE_STAGES,
  GRAPES_BOWER,
  PEACH_TREE,
  PEAR_TREE,
  BOMBSCHROOM,
  TOXIC_GAS_CLOUD_VFX,
  SKELETON,
  SKELETON_BOWMAN,
  SKELETON_BOWMAN_BOW,
  SKELETON_BOWMAN_SEPARATED,
  SKELETON_MAGE,
  SKELETON_SWORDMAN,
  SLIME_BIG_BLUE,
  SLIME_BIG_GREEN,
  SLIME_BIG_PINK,
  SLIME_BIG_RED,
  SLIME_BIG_YELLOW,
  SLIME_MEDIUM_BLUE,
  SLIME_MEDIUM_GREEN,
  SLIME_MEDIUM_PINK,
  SLIME_MEDIUM_RED,
  SLIME_MEDIUM_YELLOW,
  SLIME_SMALL_BLUE,
  SLIME_SMALL_GREEN,
  SLIME_SMALL_PINK,
  SLIME_SMALL_RED,
  SLIME_SMALL_YELLOW,
  DOORS,
  HOUSE_1_1,
  HOUSE_1_2,
  HOUSE_1_3,
  HOUSE_1_4,
  HOUSE_1_5,
  HOUSE_1_6,
  HOUSE_2_1,
  HOUSE_2_2,
  HOUSE_2_3,
  HOUSE_2_4,
  HOUSE_2_5,
  HOUSE_2_6,
  HOUSE_3_1,
  HOUSE_3_2,
  HOUSE_3_3,
  HOUSE_3_4,
  HOUSE_3_5,
  HOUSE_3_6,
  HOUSE_4_1,
  HOUSE_4_2,
  HOUSE_4_3,
  HOUSE_4_4,
  HOUSE_4_5,
  HOUSE_4_6,
  HOUSE_5_1,
  HOUSE_5_2,
  HOUSE_5_3,
  HOUSE_5_4,
  HOUSE_ABANDONED_1_1,
  HOUSE_ABANDONED_1_2,
  HOUSE_ABANDONED_1_3,
  HOUSE_ABANDONED_1_4,
  HOUSE_ABANDONED_1_5,
  HOUSE_ABANDONED_1_6,
  HOUSE_ABANDONED_2_1,
  HOUSE_ABANDONED_2_2,
  HOUSE_ABANDONED_2_3,
  HOUSE_ABANDONED_2_4,
  HOUSE_ABANDONED_2_5,
  HOUSE_ABANDONED_2_6,
  HOUSE_ABANDONED_3_1,
  HOUSE_ABANDONED_3_2,
  HOUSE_ABANDONED_3_3,
  HOUSE_ABANDONED_3_4,
  HOUSE_ABANDONED_3_5,
  HOUSE_ABANDONED_3_6,
  HOUSE_ABANDONED_4_1,
  HOUSE_ABANDONED_4_2,
  HOUSE_ABANDONED_4_3,
  HOUSE_ABANDONED_4_4,
  HOUSE_ABANDONED_4_5,
  HOUSE_ABANDONED_4_6,
  HOUSE_1_STONE_STAGES,
  HOUSE_1_WOOD_STAGES,
  HOUSE_2_STONE_STAGES,
  HOUSE_2_WOOD_STAGES,
  HOUSE_3_STONE_STAGES,
  HOUSE_3_WOOD_STAGES,
  HOUSE_4_STONE_STAGES,
  HOUSE_4_WOOD_STAGES,
  BRICK_WALL_FILLERS,
  INTERIOR_WALLS,
  STONE_WALL_FILLERS,
  WOOD_FLOOR_TILES,
  WOOD_STAIRS,
  WOOD_WALL_FILLERS,
  PLANTERS,
  BARN,
  BLACKSMITH_HOUSE,
  CHICKEN_COOP,
  GREENHOUSE_GREEN,
  GREENHOUSE_METAL,
  GREENHOUSE_WOOD,
  SILO,
  HORSE_STABLE_1,
  HORSE_STABLE_2,
  HORSE_STABLE_3,
  HORSE_STABLE_4,
  HORSE_STABLE_5,
  HORSE_STABLE_6,
  HORSE_STABLE_7,
  WINDMILL,
  WINDMILL_SAIL_ANIM,
  TENT_BIG,
  TENT_INTERIOR,
  TENT_SMALL,
  WINDOWS,
  ANVIL_ANIM,
  CHEST_ANIM,
  FURNACE_ANIM,
  GOLDEN_CHEST_ANIM,
  GOLDEN_JEWELED_CHEST_ANIM,
  INDOOR_DECOR,
  METAL_CHEST_ANIM,
  CHIMNEYS,
  HOUSE_ROOF,
  HOUSE_STONE,
  HOUSE_WOOD,
  SMOKE_1_1_ANIM,
  SMOKE_1_2_ANIM,
  SMOKE_1_3_ANIM,
  SMOKE_1_ANIM,
  SMOKE_2_ANIM,
  SMOKE_3_ANIM,
  STONE_FLOOR_1,
  STONE_FLOOR_2,
  WOOD_DOOR,
  WOOD_DOOR_ANIM,
  WOOD_FLOOR_1,
  WOOD_FLOOR_2,
  FOOD_ICONS_NO_OUTLINE,
  OTHER_ICONS_NO_OUTLINE,
  RESOURCES_ICONS_NO_OUTLINE,
  TOOL_ICONS_NO_OUTLINE,
  FOOD_ICONS_OUTLINE,
  OTHER_ICONS_OUTLINE,
  RESOURCES_ICONS_OUTLINE,
  TOOL_ICONS_OUTLINE,
  BOW_STAGES,
  LADDER,
  LANTERN_TORCH,
  SKELETON_MAGE_PROJECTILE,
  BENCHES,
  BIG_TORCH_ANIM,
  BOAT,
  CAMP_DECOR,
  CAVE_DECORATIONS,
  FENCES,
  FENCE_BIG,
  FLOWERS,
  FOUNTAIN,
  HAY_BALES,
  LANTERN,
  LANTER_POSTS,
  MINECRATS,
  NESTS,
  ORES,
  OUTDOOR_DECOR,
  BARREL_1_ANIM,
  CRATE_ANIM,
  SIGN_1_ANIM,
  SIGN_2_ANIM,
  FLOWERS_1_ANIM,
  FLOWERS_2_ANIM,
  FLOWERS_3_ANIM,
  FLOWERS_4_ANIM,
  FLOWERS_5_ANIM,
  FLOWERS_1_POTTED_ANIM,
  FLOWERS_2_POTTED_ANIM,
  FLOWERS_3_POTTED_ANIM,
  FLOWERS_4_POTTED_ANIM,
  FLOWERS_5_POTTED_ANIM,
  FLOWER_GRASS_10_ANIM,
  FLOWER_GRASS_11_ANIM,
  FLOWER_GRASS_12_ANIM,
  FLOWER_GRASS_13_ANIM,
  FLOWER_GRASS_14_ANIM,
  FLOWER_GRASS_15_ANIM,
  FLOWER_GRASS_1_ANIM,
  FLOWER_GRASS_2_ANIM,
  FLOWER_GRASS_3_ANIM,
  FLOWER_GRASS_4_ANIM,
  FLOWER_GRASS_5_ANIM,
  FLOWER_GRASS_6_ANIM,
  FLOWER_GRASS_7_ANIM,
  FLOWER_GRASS_8_ANIM,
  FLOWER_GRASS_9_ANIM,
  GRASS_1_ANIM,
  GRASS_2_ANIM,
  GRASS_3_ANIM,
  MUSCHROOM_1_ANIM,
  MUSCHROOM_2_ANIM,
  MUSCHROOM_3_ANIM,
  MUSCHROOM_4_ANIM,
  MUSCHROOM_5_ANIM,
  MUSCHROOM_6_ANIM,
  MUSCHROOM_7_ANIM,
  MUSCHROOM_8_ANIM,
  BOAT_ANIM,
  CAMPFIRE_ANIM,
  FENCE_BIG_GATE,
  FENCE_BIG_GATE_VERTICAL,
  POLE_AND_BUNTING_1_ANIM,
  POLE_AND_BUNTING_2_ANIM,
  TORCH_ANIM,
  TORCH_SMALL_ANIM,
  CAVE_ROCK_1_ANIM,
  CAVE_ROCK_2_ANIM,
  CAVE_ROCK_3_ANIM,
  CAVE_ROCK_4_ANIM,
  ROCK_10_ANIM,
  ROCK_11_ANIM,
  ROCK_12_ANIM,
  ROCK_13_ANIM,
  ROCK_14_ANIM,
  ROCK_1_ANIM,
  ROCK_2_ANIM,
  ROCK_3_ANIM,
  ROCK_4_ANIM,
  ROCK_5_ANIM,
  ROCK_6_ANIM,
  ROCK_7_ANIM,
  ROCK_8_ANIM,
  ROCK_9_ANIM,
  BRANCH_WATER_ANIM,
  LOG_1_WATER_ANIM,
  LOG_2_WATER_ANIM,
  LOG_3_WATER_ANIM,
  CATTAIL_1_ANIM,
  CATTAIL_2_ANIM,
  CATTAIL_3_ANIM,
  CATTAIL_4_ANIM,
  CATTAIL_5_ANIM,
  LILLYPAD_BROWN_1_ANIM,
  LILLYPAD_BROWN_2_ANIM,
  LILLYPAD_BROWN_3_ANIM,
  LILLYPAD_BROWN_4_ANIM,
  LILLYPAD_BROWN_5_ANIM,
  LILLYPAD_BROWN_6_ANIM,
  LILLYPAD_GREEN_1_ANIM,
  LILLYPAD_GREEN_2_ANIM,
  LILLYPAD_GREEN_3_ANIM,
  LILLYPAD_GREEN_4_ANIM,
  LILLYPAD_GREEN_5_ANIM,
  LILLYPAD_GREEN_6_ANIM,
  LILLYPAD_PURPLE_1_ANIM,
  LILLYPAD_PURPLE_2_ANIM,
  LILLYPAD_PURPLE_3_ANIM,
  LILLYPAD_PURPLE_4_ANIM,
  LILLYPAD_PURPLE_5_ANIM,
  LILLYPAD_PURPLE_6_ANIM,
  LILLYPAD_RED_1_ANIM,
  LILLYPAD_RED_2_ANIM,
  LILLYPAD_RED_3_ANIM,
  LILLYPAD_RED_4_ANIM,
  LILLYPAD_RED_5_ANIM,
  LILLYPAD_RED_6_ANIM,
  WATER_GRASS_1_ANIM,
  WATER_GRASS_2_ANIM,
  ROCK_10_WATER_ANIM,
  ROCK_15_WATER_ANIM,
  ROCK_16_WATER_ANIM,
  ROCK_3_WATER_ANIM,
  ROCK_4_WATER_ANIM,
  ROCK_5_WATER_ANIM,
  ROCK_6_WATER_ANIM,
  ROCK_7_WATER_ANIM,
  ROCK_8_WATER_ANIM,
  ROCK_9_WATER_ANIM,
  PICNIC_BASKET,
  SCARECROWS,
  SIGNS,
  STONE_FENCE_BIG,
  STONE_FENCE_SMALL,
  WATER_TROUGHS,
  WELL,
  WHITE_FENCE,
  PANTS_BLUE_ATTACK,
  PANTS_BLUE_AXE,
  PANTS_BLUE_BOW,
  PANTS_BLUE_CLIMB,
  PANTS_BLUE_DEATH,
  PANTS_BLUE_FISHING,
  PANTS_BLUE_HOE,
  PANTS_BLUE_HORSE,
  PANTS_BLUE_IDLE,
  PANTS_BLUE_JUMP,
  PANTS_BLUE_PICKAXE,
  PANTS_BLUE_PUSH,
  PANTS_BLUE_ROLL,
  PANTS_BLUE_RUNNING,
  PANTS_BLUE_WATERINGCAN,
  SHIRT_GREEN_ATTACK,
  SHIRT_GREEN_AXE,
  SHIRT_GREEN_BOW,
  SHIRT_GREEN_CLIMB,
  SHIRT_GREEN_DEATH,
  SHIRT_GREEN_FISHING,
  SHIRT_GREEN_HOE,
  SHIRT_GREEN_HORSE,
  SHIRT_GREEN_IDLE,
  SHIRT_GREEN_JUMP,
  SHIRT_GREEN_PICKAXE,
  SHIRT_GREEN_PUSH,
  SHIRT_GREEN_ROLL,
  SHIRT_GREEN_RUNNING,
  SHIRT_GREEN_WATERINGCAN,
  SHOES_BROWN_ATTACK,
  SHOES_BROWN_AXE,
  SHOES_BROWN_BOW,
  SHOES_BROWN_CLIMB,
  SHOES_BROWN_DEATH,
  SHOES_BROWN_FISHING,
  SHOES_BROWN_HOE,
  SHOES_BROWN_HORSE,
  SHOES_BROWN_IDLE,
  SHOES_BROWN_JUMP,
  SHOES_BROWN_PICKAXE,
  SHOES_BROWN_PUSH,
  SHOES_BROWN_ROLL,
  SHOES_BROWN_RUNNING,
  SHOES_BROWN_WATERINGCAN,
  MEDIUM_HAIR_BROWN_ATTACK,
  MEDIUM_HAIR_BROWN_AXE,
  MEDIUM_HAIR_BROWN_BOW,
  MEDIUM_HAIR_BROWN_CLIMB,
  MEDIUM_HAIR_BROWN_DEATH,
  MEDIUM_HAIR_BROWN_FISHING,
  MEDIUM_HAIR_BROWN_HOE,
  MEDIUM_HAIR_BROWN_HORSE,
  MEDIUM_HAIR_BROWN_IDLE,
  MEDIUM_HAIR_BROWN_JUMP,
  MEDIUM_HAIR_BROWN_PICKAXE,
  MEDIUM_HAIR_BROWN_PUSH,
  MEDIUM_HAIR_BROWN_ROLL,
  MEDIUM_HAIR_BROWN_RUNNING,
  MEDIUM_HAIR_BROWN_WATERINGCAN,
  HANDS_BARE_ATTACK,
  HANDS_BARE_AXE,
  HANDS_BARE_BOW,
  HANDS_BARE_CLIMB,
  HANDS_BARE_DEATH,
  HANDS_BARE_FISHING,
  HANDS_BARE_HOE,
  HANDS_BARE_HOLDING_IDLE,
  HANDS_BARE_HOLDING_RUNNING,
  HANDS_BARE_HORSE,
  HANDS_BARE_IDLE,
  HANDS_BARE_JUMP,
  HANDS_BARE_LANTERN_IDLE,
  HANDS_BARE_LANTERN_RUNNING,
  HANDS_BARE_PICKAXE,
  HANDS_BARE_PUSH,
  HANDS_BARE_ROLL,
  HANDS_BARE_RUNNING,
  HANDS_BARE_TORCH_IDLE,
  HANDS_BARE_TORCH_RUNNING,
  HANDS_BARE_WATERINGCAN,
  PLAYER_BASE_ATTACK,
  PLAYER_BASE_AXE,
  PLAYER_BASE_BOW,
  PLAYER_BASE_CLIMB,
  PLAYER_BASE_DEATH,
  PLAYER_BASE_FISHING,
  PLAYER_BASE_HOE,
  PLAYER_BASE_HORSE,
  PLAYER_BASE_IDLE,
  PLAYER_BASE_JUMP,
  PLAYER_BASE_PICKAXE,
  PLAYER_BASE_PUSH,
  PLAYER_BASE_ROLL,
  PLAYER_BASE_RUNNING,
  PLAYER_BASE_WATERINGCAN,
  WOODEN_BOW,
  IRON_AXE,
  IRON_HOE,
  IRON_PICKAXE,
  IRON_SWORD,
  IRON_WATERINGCAN,
  LANTERN_IDLE,
  LANTERN_RUNNING,
  TORCH_IDLE,
  TORCH_RUNNING,
  WOODEN_FISHINGROD,
  BEACH_DECOR_TILES,
  BEACH_TILES,
  BRIDGE_STONE_HORIZONTAL,
  BRIDGE_STONE_VERTICAL,
  BRIDGE_WOOD,
  CAVE_DOOR,
  CAVE_DOORWAY_1,
  CAVE_FLOOR,
  CAVE_FLOOR_1,
  CAVE_FLOOR_2,
  CAVE_FLOOR_DECORATION,
  CAVE_FLOOR_LADDER,
  CAVE_FLOOR_MIDDLE,
  CAVE_SUPPORT_1,
  CAVE_SUPPORT_2,
  CAVE_WALLS,
  CAVE_WALL_SUPPORT,
  CAVE_WATER,
  CAVE_WATER_ANIMATION,
  RAILS,
  CAVE_ENTRANCE,
  STONE_CLIFF_1_CAVE_ENTRANCE,
  STONE_CLIFF_1_TILE,
  STONE_CLIFF_2_CAVE_ENTRANCE,
  STONE_CLIFF_2_TILE,
  STONE_CLIFF_3_CAVE_ENTRANCE,
  STONE_CLIFF_3_TILE,
  STONE_CLIFF_4_CAVE_ENTRANCE,
  STONE_CLIFF_4_TILE,
  COBBLE_ROAD_1,
  COBBLE_ROAD_2,
  FARMLAND_TILE,
  FARMLAND_WET_TILE,
  GRASS_1_MIDDLE,
  GRASS_2_MIDDLE,
  GRASS_3_MIDDLE,
  GRASS_4_MIDDLE,
  GRASS_TILES_1,
  GRASS_TILES_1_BLOB_TEST,
  GRASS_TILES_1_BLOB_TEST_1,
  GRASS_TILES_2,
  GRASS_TILES_3,
  GRASS_TILES_4,
  PATH_DECORATION,
  PATH_MIDDLE,
  PICNIC_BLANKETS,
  FISH_ANIMATED_TILE,
  WATER_DECORATION,
  WATER_FOAM_ANIMATION,
  WATER_MIDDLE,
  WATER_MIDDLE_ANIM_1,
  WATER_MIDDLE_ANIM_2,
  WATER_STONE_TILE_1,
  WATER_STONE_TILE_1_ANIM,
  WATER_STONE_TILE_2,
  WATER_STONE_TILE_2_ANIM,
  WATER_STONE_TILE_3,
  WATER_STONE_TILE_3_ANIM,
  WATER_STONE_TILE_4,
  WATER_STONE_TILE_4_ANIM,
  WATER_TILE_1,
  WATER_TILE_1_ANIM,
  WATER_TILE_2,
  WATER_TILE_2_ANIM,
  WATER_TILE_3,
  WATER_TILE_3_ANIM,
  WATER_TILE_4,
  WATER_TILE_4_ANIM,
  WATERFALL_1,
  WATERFALL_2,
  WATERFALL_3,
  WATERFALL_4,
  WATERFALL_5,
  WATERFALL_6,
  WATERFALL_7,
  WATERFALL_8,
  BIG_BIRCH_TREE,
  BIG_FRUIT_TREE,
  BIG_OAK_TREE,
  BIG_SPRUCE_TREE,
  BIRCH_LEAF_PARTICLE,
  MEDIUM_BIRCH_TREE,
  MEDIUM_FRUIT_TREE,
  MEDIUM_OAK_TREE,
  MEDIUM_SPRUCE_TREE,
  OAK_LEAF_PARTICLE,
  SMALL_BIRCH_TREE,
  SMALL_FRUIT_TREE,
  SMALL_OAK_TREE,
  SMALL_SPRUCE_TREE,
  SPRUCE_NEEDLE_PARTICLE,
  CLOUDS,
  RAIN_DROP,
  RAIN_DROP_IMPACT,
  WIND_ANIM,
} from "./imports";

export const ASSETS_CONSTANT_1 = [
  { tileSet: BEE_FLYING_ANIMATION, name: "Bee_Flying_Animation" },
  { tileSet: BEE_HIVE, name: "Bee_Hive" },
  { tileSet: BEE_NEST, name: "Bee_Nest" },
  { tileSet: BUTTERFLY, name: "Butterfly" },
  { tileSet: CHICKEN_01, name: "Chicken_01" },
  { tileSet: CHICKEN_02, name: "Chicken_02" },
  { tileSet: CHICKEN_03, name: "Chicken_03" },
  { tileSet: CHICKEN_04, name: "Chicken_04" },
  { tileSet: CHICKEN_05, name: "Chicken_05" },
  { tileSet: CHICKEN_06, name: "Chicken_06" },
  { tileSet: CHICKEN_07, name: "Chicken_07" },
  { tileSet: CHICKEN_08, name: "Chicken_08" },
  { tileSet: CHICKEN_09, name: "Chicken_09" },
  { tileSet: CHICKEN_10, name: "Chicken_10" },
  { tileSet: CHICKEN_11, name: "Chicken_11" },
  { tileSet: CHICKEN_12, name: "Chicken_12" },
  { tileSet: CHICKEN_13, name: "Chicken_13" },
  { tileSet: CHICKEN_14, name: "Chicken_14" },
  { tileSet: CHICKEN_15, name: "Chicken_15" },
  { tileSet: CHICKEN_16, name: "Chicken_16" },
  { tileSet: CHICKEN_17, name: "Chicken_17" },
  { tileSet: CHICKEN_18, name: "Chicken_18" },
  { tileSet: COW_01, name: "Cow_01" },
  { tileSet: COW_02, name: "Cow_02" },
  { tileSet: COW_03, name: "Cow_03" },
  { tileSet: COW_04, name: "Cow_04" },
  { tileSet: COW_05, name: "Cow_05" },
  { tileSet: COW_06, name: "Cow_06" },
  { tileSet: COW_07, name: "Cow_07" },
  { tileSet: COW_08, name: "Cow_08" },
  { tileSet: COW_09, name: "Cow_09" },
  { tileSet: HORSE_01, name: "Horse_01" },
  { tileSet: ALBINO_KAPYBARA_BUBBLES, name: "Albino_Kapybara_Bubbles" },
  { tileSet: ALBINO_KAPYBARA_DIVE, name: "Albino_Kapybara_Dive" },
  { tileSet: ALBINO_KAPYBARA_EMERGE, name: "Albino_Kapybara_Emerge" },
  { tileSet: ALBINO_KAPYBARA_IDLE, name: "Albino_Kapybara_Idle" },
  { tileSet: ALBINO_KAPYBARA_LOOKAROUND, name: "Albino_Kapybara_LookAround" },
  { tileSet: ALBINO_KAPYBARA_LOOKAROUND_SUBMERGED, name: "Albino_Kapybara_LookAround_submerged" },
  { tileSet: KAPYBARA_BUBBLES, name: "Kapybara_Bubbles" },
  { tileSet: KAPYBARA_DIVE, name: "Kapybara_Dive" },
  { tileSet: KAPYBARA_EMERGE, name: "Kapybara_Emerge" },
  { tileSet: KAPYBARA_IDLE, name: "Kapybara_Idle" },
  { tileSet: KAPYBARA_LOOKAROUND, name: "Kapybara_LookAround" },
  { tileSet: KAPYBARA_LOOKAROUND_SUBMERGED, name: "Kapybara_LookAround_submerged" },
  { tileSet: PIG_01, name: "Pig_01" },
  { tileSet: PIG_02, name: "Pig_02" },
  { tileSet: PIG_03, name: "Pig_03" },
  { tileSet: PIG_04, name: "Pig_04" },
  { tileSet: PIG_05, name: "Pig_05" },
  { tileSet: PIG_06, name: "Pig_06" },
  { tileSet: PIG_07, name: "Pig_07" },
  { tileSet: PIG_08, name: "Pig_08" },
  { tileSet: PIG_09, name: "Pig_09" },
  { tileSet: PIG_10, name: "Pig_10" },
  { tileSet: PIG_11, name: "Pig_11" },
  { tileSet: PIG_12, name: "Pig_12" },
  { tileSet: PIG_13, name: "Pig_13" },
  { tileSet: PIG_14, name: "Pig_14" },
  { tileSet: PIG_15, name: "Pig_15" },
  { tileSet: PIG_16, name: "Pig_16" },
  { tileSet: SHEEP_01, name: "Sheep_01" },
  { tileSet: SHEEP_02, name: "Sheep_02" },
  { tileSet: SHEEP_03, name: "Sheep_03" },
  { tileSet: SHEEP_04, name: "Sheep_04" },
  { tileSet: SHEEP_05, name: "Sheep_05" },
  { tileSet: SHEEP_06, name: "Sheep_06" },
  { tileSet: SHEEP_07, name: "Sheep_07" },
  { tileSet: SHEEP_08, name: "Sheep_08" },
  { tileSet: SHEEP_09, name: "Sheep_09" },
  { tileSet: APPLE_TREE, name: "Apple_Tree" },
  { tileSet: BERRIES, name: "Berries" },
  { tileSet: CHERRY_TREE, name: "Cherry_Tree" },
  { tileSet: CROPS, name: "Crops" },
  { tileSet: FRUIT_TREES_FRUIT_OBJECTS, name: "Fruit_Trees_Fruit_Objects" },
  { tileSet: FRUIT_TREE_STAGES, name: "Fruit_Tree_Stages" },
  { tileSet: GRAPES_BOWER, name: "Grapes_Bower" },
  { tileSet: PEACH_TREE, name: "Peach_Tree" },
  { tileSet: PEAR_TREE, name: "Pear_Tree" },
  { tileSet: BOMBSCHROOM, name: "Bombschroom" },
  { tileSet: TOXIC_GAS_CLOUD_VFX, name: "Toxic_Gas_Cloud_VFX" },
  { tileSet: SKELETON, name: "Skeleton" },
  { tileSet: SKELETON_BOWMAN, name: "Skeleton_Bowman" },
  { tileSet: SKELETON_BOWMAN_BOW, name: "Skeleton_Bowman_Bow" },
  { tileSet: SKELETON_BOWMAN_SEPARATED, name: "Skeleton_Bowman_Separated" },
  { tileSet: SKELETON_MAGE, name: "Skeleton_Mage" },
  { tileSet: SKELETON_SWORDMAN, name: "Skeleton_Swordman" },
  { tileSet: SLIME_BIG_BLUE, name: "Slime_Big_Blue" },
  { tileSet: SLIME_BIG_GREEN, name: "Slime_Big_Green" },
  { tileSet: SLIME_BIG_PINK, name: "Slime_Big_Pink" },
  { tileSet: SLIME_BIG_RED, name: "Slime_Big_Red" },
  { tileSet: SLIME_BIG_YELLOW, name: "Slime_Big_Yellow" },
  { tileSet: SLIME_MEDIUM_BLUE, name: "Slime_Medium_Blue" },
  { tileSet: SLIME_MEDIUM_GREEN, name: "Slime_Medium_Green" },
  { tileSet: SLIME_MEDIUM_PINK, name: "Slime_Medium_Pink" },
  { tileSet: SLIME_MEDIUM_RED, name: "Slime_Medium_Red" },
  { tileSet: SLIME_MEDIUM_YELLOW, name: "Slime_Medium_Yellow" },
  { tileSet: SLIME_SMALL_BLUE, name: "Slime_Small_Blue" },
  { tileSet: SLIME_SMALL_GREEN, name: "Slime_Small_Green" },
  { tileSet: SLIME_SMALL_PINK, name: "Slime_Small_Pink" },
  { tileSet: SLIME_SMALL_RED, name: "Slime_Small_Red" },
  { tileSet: SLIME_SMALL_YELLOW, name: "Slime_Small_Yellow" },
  { tileSet: DOORS, name: "Doors" },
  { tileSet: HOUSE_1_1, name: "House_1_1" },
  { tileSet: HOUSE_1_2, name: "House_1_2" },
  { tileSet: HOUSE_1_3, name: "House_1_3" },
  { tileSet: HOUSE_1_4, name: "House_1_4" },
  { tileSet: HOUSE_1_5, name: "House_1_5" },
  { tileSet: HOUSE_1_6, name: "House_1_6" },
  { tileSet: HOUSE_2_1, name: "House_2_1" },
  { tileSet: HOUSE_2_2, name: "House_2_2" },
  { tileSet: HOUSE_2_3, name: "House_2_3" },
  { tileSet: HOUSE_2_4, name: "House_2_4" },
  { tileSet: HOUSE_2_5, name: "House_2_5" },
  { tileSet: HOUSE_2_6, name: "House_2_6" },
  { tileSet: HOUSE_3_1, name: "House_3_1" },
  { tileSet: HOUSE_3_2, name: "House_3_2" },
  { tileSet: HOUSE_3_3, name: "House_3_3" },
  { tileSet: HOUSE_3_4, name: "House_3_4" },
  { tileSet: HOUSE_3_5, name: "House_3_5" },
  { tileSet: HOUSE_3_6, name: "House_3_6" },
  { tileSet: HOUSE_4_1, name: "House_4_1" },
  { tileSet: HOUSE_4_2, name: "House_4_2" },
  { tileSet: HOUSE_4_3, name: "House_4_3" },
  { tileSet: HOUSE_4_4, name: "House_4_4" },
  { tileSet: HOUSE_4_5, name: "House_4_5" },
  { tileSet: HOUSE_4_6, name: "House_4_6" },
  { tileSet: HOUSE_5_1, name: "House_5_1" },
  { tileSet: HOUSE_5_2, name: "House_5_2" },
  { tileSet: HOUSE_5_3, name: "House_5_3" },
  { tileSet: HOUSE_5_4, name: "House_5_4" },
  { tileSet: HOUSE_ABANDONED_1_1, name: "House_Abandoned_1_1" },
  { tileSet: HOUSE_ABANDONED_1_2, name: "House_Abandoned_1_2" },
  { tileSet: HOUSE_ABANDONED_1_3, name: "House_Abandoned_1_3" },
  { tileSet: HOUSE_ABANDONED_1_4, name: "House_Abandoned_1_4" },
  { tileSet: HOUSE_ABANDONED_1_5, name: "House_Abandoned_1_5" },
  { tileSet: HOUSE_ABANDONED_1_6, name: "House_Abandoned_1_6" },
  { tileSet: HOUSE_ABANDONED_2_1, name: "House_Abandoned_2_1" },
  { tileSet: HOUSE_ABANDONED_2_2, name: "House_Abandoned_2_2" },
  { tileSet: HOUSE_ABANDONED_2_3, name: "House_Abandoned_2_3" },
  { tileSet: HOUSE_ABANDONED_2_4, name: "House_Abandoned_2_4" },
  { tileSet: HOUSE_ABANDONED_2_5, name: "House_Abandoned_2_5" },
  { tileSet: HOUSE_ABANDONED_2_6, name: "House_Abandoned_2_6" },
  { tileSet: HOUSE_ABANDONED_3_1, name: "House_Abandoned_3_1" },
  { tileSet: HOUSE_ABANDONED_3_2, name: "House_Abandoned_3_2" },
  { tileSet: HOUSE_ABANDONED_3_3, name: "House_Abandoned_3_3" },
  { tileSet: HOUSE_ABANDONED_3_4, name: "House_Abandoned_3_4" },
  { tileSet: HOUSE_ABANDONED_3_5, name: "House_Abandoned_3_5" },
  { tileSet: HOUSE_ABANDONED_3_6, name: "House_Abandoned_3_6" },
  { tileSet: HOUSE_ABANDONED_4_1, name: "House_Abandoned_4_1" },
  { tileSet: HOUSE_ABANDONED_4_2, name: "House_Abandoned_4_2" },
  { tileSet: HOUSE_ABANDONED_4_3, name: "House_Abandoned_4_3" },
  { tileSet: HOUSE_ABANDONED_4_4, name: "House_Abandoned_4_4" },
  { tileSet: HOUSE_ABANDONED_4_5, name: "House_Abandoned_4_5" },
  { tileSet: HOUSE_ABANDONED_4_6, name: "House_Abandoned_4_6" },
  { tileSet: HOUSE_1_STONE_STAGES, name: "House_1_Stone_Stages" },
  { tileSet: HOUSE_1_WOOD_STAGES, name: "House_1_wood_Stages" },
  { tileSet: HOUSE_2_STONE_STAGES, name: "House_2_Stone_Stages" },
  { tileSet: HOUSE_2_WOOD_STAGES, name: "House_2_Wood_Stages" },
  { tileSet: HOUSE_3_STONE_STAGES, name: "House_3_Stone_Stages" },
  { tileSet: HOUSE_3_WOOD_STAGES, name: "House_3_Wood_Stages" },
  { tileSet: HOUSE_4_STONE_STAGES, name: "House_4_Stone_Stages" },
  { tileSet: HOUSE_4_WOOD_STAGES, name: "House_4_Wood_Stages" },
  { tileSet: BRICK_WALL_FILLERS, name: "Brick_Wall_Fillers" },
  { tileSet: INTERIOR_WALLS, name: "Interior_Walls" },
  { tileSet: STONE_WALL_FILLERS, name: "Stone_Wall_Fillers" },
  { tileSet: WOOD_FLOOR_TILES, name: "Wood_Floor_Tiles" },
  { tileSet: WOOD_STAIRS, name: "Wood_Stairs" },
  { tileSet: WOOD_WALL_FILLERS, name: "Wood_Wall_Fillers" },
  { tileSet: PLANTERS, name: "Planters" },
  { tileSet: BARN, name: "Barn" },
  { tileSet: BLACKSMITH_HOUSE, name: "Blacksmith_House" },
  { tileSet: CHICKEN_COOP, name: "Chicken_Coop" },
  { tileSet: GREENHOUSE_GREEN, name: "GreenHouse_Green" },
  { tileSet: GREENHOUSE_METAL, name: "GreenHouse_Metal" },
  { tileSet: GREENHOUSE_WOOD, name: "GreenHouse_Wood" },
  { tileSet: SILO, name: "Silo" },
  { tileSet: HORSE_STABLE_1, name: "Horse_Stable_1" },
  { tileSet: HORSE_STABLE_2, name: "Horse_Stable_2" },
  { tileSet: HORSE_STABLE_3, name: "Horse_Stable_3" },
  { tileSet: HORSE_STABLE_4, name: "Horse_Stable_4" },
  { tileSet: HORSE_STABLE_5, name: "Horse_Stable_5" },
  { tileSet: HORSE_STABLE_6, name: "Horse_Stable_6" },
  { tileSet: HORSE_STABLE_7, name: "Horse_Stable_7" },
  { tileSet: WINDMILL, name: "Windmill" },
  { tileSet: WINDMILL_SAIL_ANIM, name: "Windmill_Sail_Anim" },
  { tileSet: TENT_BIG, name: "Tent_Big" },
  { tileSet: TENT_INTERIOR, name: "Tent_Interior" },
  { tileSet: TENT_SMALL, name: "Tent_Small" },
  { tileSet: WINDOWS, name: "Windows" },
  { tileSet: ANVIL_ANIM, name: "Anvil_Anim" },
  { tileSet: CHEST_ANIM, name: "Chest_Anim" },
  { tileSet: FURNACE_ANIM, name: "Furnace_Anim" },
  { tileSet: GOLDEN_CHEST_ANIM, name: "Golden_Chest_Anim" },
  { tileSet: GOLDEN_JEWELED_CHEST_ANIM, name: "Golden_Jeweled_Chest_Anim" },
  { tileSet: INDOOR_DECOR, name: "Indoor_Decor" },
  { tileSet: METAL_CHEST_ANIM, name: "Metal_Chest_Anim" },
  { tileSet: CHIMNEYS, name: "Chimneys" },
  { tileSet: HOUSE_ROOF, name: "House_Roof" },
  { tileSet: HOUSE_STONE, name: "House_Stone" },
  { tileSet: HOUSE_WOOD, name: "House_Wood" },
  { tileSet: SMOKE_1_1_ANIM, name: "smoke_1.1_Anim" },
  { tileSet: SMOKE_1_2_ANIM, name: "smoke_1.2_Anim" },
  { tileSet: SMOKE_1_3_ANIM, name: "smoke_1.3_Anim" },
  { tileSet: SMOKE_1_ANIM, name: "smoke_1_Anim" },
  { tileSet: SMOKE_2_ANIM, name: "smoke_2_Anim" },
  { tileSet: SMOKE_3_ANIM, name: "smoke_3_Anim" },
  { tileSet: STONE_FLOOR_1, name: "Stone_Floor_1" },
  { tileSet: STONE_FLOOR_2, name: "Stone_Floor_2" },
  { tileSet: WOOD_DOOR, name: "Wood_Door" },
  { tileSet: WOOD_DOOR_ANIM, name: "Wood_Door_Anim" },
  { tileSet: WOOD_FLOOR_1, name: "Wood_Floor_1" },
  { tileSet: WOOD_FLOOR_2, name: "Wood_Floor_2" },
  { tileSet: FOOD_ICONS_NO_OUTLINE, name: "Food_Icons_NO_Outline" },
  { tileSet: OTHER_ICONS_NO_OUTLINE, name: "Other_Icons_NO_Outline" },
  { tileSet: RESOURCES_ICONS_NO_OUTLINE, name: "Resources_Icons_NO_Outline" },
  { tileSet: TOOL_ICONS_NO_OUTLINE, name: "Tool_Icons_NO_Outline" },
  { tileSet: FOOD_ICONS_OUTLINE, name: "Food_Icons_Outline" },
  { tileSet: OTHER_ICONS_OUTLINE, name: "Other_Icons_Outline" },
  { tileSet: RESOURCES_ICONS_OUTLINE, name: "Resources_Icons_Outline" },
  { tileSet: TOOL_ICONS_OUTLINE, name: "Tool_Icons_Outline" },
  { tileSet: BOW_STAGES, name: "Bow_Stages" },
  { tileSet: LADDER, name: "Ladder" },
  { tileSet: LANTERN_TORCH, name: "Lantern_Torch" },
  { tileSet: SKELETON_MAGE_PROJECTILE, name: "Skeleton_Mage_Projectile" },
  { tileSet: BENCHES, name: "Benches" },
  { tileSet: BIG_TORCH_ANIM, name: "Big_Torch_Anim" },
  { tileSet: BOAT, name: "Boat" },
  { tileSet: CAMP_DECOR, name: "Camp_Decor" },
  { tileSet: CAVE_DECORATIONS, name: "Cave_Decorations" },
  { tileSet: FENCES, name: "Fences" },
  { tileSet: FENCE_BIG, name: "Fence_Big" },
  { tileSet: FLOWERS, name: "Flowers" },
  { tileSet: FOUNTAIN, name: "Fountain" },
  { tileSet: HAY_BALES, name: "Hay_Bales" },
  { tileSet: LANTERN, name: "Lantern" },
  { tileSet: LANTER_POSTS, name: "Lanter_Posts" },
  { tileSet: MINECRATS, name: "Minecrats" },
  { tileSet: NESTS, name: "Nests" },
  { tileSet: ORES, name: "Ores" },
  { tileSet: OUTDOOR_DECOR, name: "Outdoor_Decor" },
  { tileSet: BARREL_1_ANIM, name: "Barrel_1_Anim" },
  { tileSet: CRATE_ANIM, name: "Crate_Anim" },
  { tileSet: SIGN_1_ANIM, name: "Sign_1_Anim" },
  { tileSet: SIGN_2_ANIM, name: "Sign_2_Anim" },
  { tileSet: FLOWERS_1_ANIM, name: "Flowers_1_Anim" },
  { tileSet: FLOWERS_2_ANIM, name: "Flowers_2_Anim" },
  { tileSet: FLOWERS_3_ANIM, name: "Flowers_3_Anim" },
  { tileSet: FLOWERS_4_ANIM, name: "Flowers_4_Anim" },
  { tileSet: FLOWERS_5_ANIM, name: "Flowers_5_Anim" },
  { tileSet: FLOWERS_1_POTTED_ANIM, name: "Flowers_1_Potted_Anim" },
  { tileSet: FLOWERS_2_POTTED_ANIM, name: "Flowers_2_Potted_Anim" },
  { tileSet: FLOWERS_3_POTTED_ANIM, name: "Flowers_3_Potted_Anim" },
  { tileSet: FLOWERS_4_POTTED_ANIM, name: "Flowers_4_Potted_Anim" },
  { tileSet: FLOWERS_5_POTTED_ANIM, name: "Flowers_5_Potted_Anim" },
  { tileSet: FLOWER_GRASS_10_ANIM, name: "Flower_Grass_10_Anim" },
  { tileSet: FLOWER_GRASS_11_ANIM, name: "Flower_Grass_11_Anim" },
  { tileSet: FLOWER_GRASS_12_ANIM, name: "Flower_Grass_12_Anim" },
  { tileSet: FLOWER_GRASS_13_ANIM, name: "Flower_Grass_13_Anim" },
  { tileSet: FLOWER_GRASS_14_ANIM, name: "Flower_Grass_14_Anim" },
  { tileSet: FLOWER_GRASS_15_ANIM, name: "Flower_Grass_15_Anim" },
  { tileSet: FLOWER_GRASS_1_ANIM, name: "Flower_Grass_1_Anim" },
  { tileSet: FLOWER_GRASS_2_ANIM, name: "Flower_Grass_2_Anim" },
  { tileSet: FLOWER_GRASS_3_ANIM, name: "Flower_Grass_3_Anim" },
  { tileSet: FLOWER_GRASS_4_ANIM, name: "Flower_Grass_4_Anim" },
  { tileSet: FLOWER_GRASS_5_ANIM, name: "Flower_Grass_5_Anim" },
  { tileSet: FLOWER_GRASS_6_ANIM, name: "Flower_Grass_6_Anim" },
  { tileSet: FLOWER_GRASS_7_ANIM, name: "Flower_Grass_7_Anim" },
  { tileSet: FLOWER_GRASS_8_ANIM, name: "Flower_Grass_8_Anim" },
  { tileSet: FLOWER_GRASS_9_ANIM, name: "Flower_Grass_9_Anim" },
  { tileSet: GRASS_1_ANIM, name: "Grass_1_Anim" },
  { tileSet: GRASS_2_ANIM, name: "Grass_2_Anim" },
  { tileSet: GRASS_3_ANIM, name: "Grass_3_Anim" },
  { tileSet: MUSCHROOM_1_ANIM, name: "muschroom_1_Anim" },
  { tileSet: MUSCHROOM_2_ANIM, name: "muschroom_2_Anim" },
  { tileSet: MUSCHROOM_3_ANIM, name: "muschroom_3_Anim" },
  { tileSet: MUSCHROOM_4_ANIM, name: "muschroom_4_Anim" },
  { tileSet: MUSCHROOM_5_ANIM, name: "muschroom_5_Anim" },
  { tileSet: MUSCHROOM_6_ANIM, name: "muschroom_6_Anim" },
  { tileSet: MUSCHROOM_7_ANIM, name: "muschroom_7_Anim" },
  { tileSet: MUSCHROOM_8_ANIM, name: "muschroom_8_Anim" },
  { tileSet: BOAT_ANIM, name: "Boat_Anim" },
  { tileSet: CAMPFIRE_ANIM, name: "Campfire_Anim" },
  { tileSet: FENCE_BIG_GATE, name: "Fence_Big_Gate" },
  { tileSet: FENCE_BIG_GATE_VERTICAL, name: "Fence_Big_Gate_Vertical" },
  { tileSet: POLE_AND_BUNTING_1_ANIM, name: "Pole_and_Bunting_1_Anim" },
  { tileSet: POLE_AND_BUNTING_2_ANIM, name: "Pole_and_Bunting_2_Anim" },
  { tileSet: TORCH_ANIM, name: "Torch_Anim" },
  { tileSet: TORCH_SMALL_ANIM, name: "Torch_small_anim" },
  { tileSet: CAVE_ROCK_1_ANIM, name: "Cave_Rock_1_Anim" },
  { tileSet: CAVE_ROCK_2_ANIM, name: "Cave_Rock_2_Anim" },
  { tileSet: CAVE_ROCK_3_ANIM, name: "Cave_Rock_3_Anim" },
  { tileSet: CAVE_ROCK_4_ANIM, name: "Cave_Rock_4_Anim" },
  { tileSet: ROCK_10_ANIM, name: "Rock_10_Anim" },
  { tileSet: ROCK_11_ANIM, name: "Rock_11_Anim" },
  { tileSet: ROCK_12_ANIM, name: "Rock_12_Anim" },
  { tileSet: ROCK_13_ANIM, name: "Rock_13_Anim" },
  { tileSet: ROCK_14_ANIM, name: "Rock_14_Anim" },
  { tileSet: ROCK_1_ANIM, name: "Rock_1_Anim" },
  { tileSet: ROCK_2_ANIM, name: "Rock_2_Anim" },
  { tileSet: ROCK_3_ANIM, name: "Rock_3_Anim" },
  { tileSet: ROCK_4_ANIM, name: "Rock_4_Anim" },
  { tileSet: ROCK_5_ANIM, name: "Rock_5_Anim" },
  { tileSet: ROCK_6_ANIM, name: "Rock_6_Anim" },
  { tileSet: ROCK_7_ANIM, name: "Rock_7_Anim" },
  { tileSet: ROCK_8_ANIM, name: "Rock_8_Anim" },
  { tileSet: ROCK_9_ANIM, name: "Rock_9_Anim" },
  { tileSet: BRANCH_WATER_ANIM, name: "Branch_Water_Anim" },
  { tileSet: LOG_1_WATER_ANIM, name: "Log_1_Water_Anim" },
  { tileSet: LOG_2_WATER_ANIM, name: "Log_2_Water_Anim" },
  { tileSet: LOG_3_WATER_ANIM, name: "Log_3_Water_Anim" },
  { tileSet: CATTAIL_1_ANIM, name: "Cattail_1_Anim" },
  { tileSet: CATTAIL_2_ANIM, name: "Cattail_2_Anim" },
  { tileSet: CATTAIL_3_ANIM, name: "Cattail_3_Anim" },
  { tileSet: CATTAIL_4_ANIM, name: "Cattail_4_Anim" },
  { tileSet: CATTAIL_5_ANIM, name: "Cattail_5_Anim" },
  { tileSet: LILLYPAD_BROWN_1_ANIM, name: "Lillypad_Brown_1_Anim" },
  { tileSet: LILLYPAD_BROWN_2_ANIM, name: "Lillypad_Brown_2_Anim" },
  { tileSet: LILLYPAD_BROWN_3_ANIM, name: "Lillypad_Brown_3_Anim" },
  { tileSet: LILLYPAD_BROWN_4_ANIM, name: "Lillypad_Brown_4_Anim" },
  { tileSet: LILLYPAD_BROWN_5_ANIM, name: "Lillypad_Brown_5_Anim" },
  { tileSet: LILLYPAD_BROWN_6_ANIM, name: "Lillypad_Brown_6_Anim" },
  { tileSet: LILLYPAD_GREEN_1_ANIM, name: "Lillypad_Green_1_Anim" },
  { tileSet: LILLYPAD_GREEN_2_ANIM, name: "Lillypad_Green_2_Anim" },
  { tileSet: LILLYPAD_GREEN_3_ANIM, name: "Lillypad_Green_3_Anim" },
  { tileSet: LILLYPAD_GREEN_4_ANIM, name: "Lillypad_Green_4_Anim" },
  { tileSet: LILLYPAD_GREEN_5_ANIM, name: "Lillypad_Green_5_Anim" },
  { tileSet: LILLYPAD_GREEN_6_ANIM, name: "Lillypad_Green_6_Anim" },
  { tileSet: LILLYPAD_PURPLE_1_ANIM, name: "Lillypad_Purple_1_Anim" },
  { tileSet: LILLYPAD_PURPLE_2_ANIM, name: "Lillypad_Purple_2_Anim" },
  { tileSet: LILLYPAD_PURPLE_3_ANIM, name: "Lillypad_Purple_3_Anim" },
  { tileSet: LILLYPAD_PURPLE_4_ANIM, name: "Lillypad_Purple_4_Anim" },
  { tileSet: LILLYPAD_PURPLE_5_ANIM, name: "Lillypad_Purple_5_Anim" },
  { tileSet: LILLYPAD_PURPLE_6_ANIM, name: "Lillypad_Purple_6_Anim" },
  { tileSet: LILLYPAD_RED_1_ANIM, name: "Lillypad_Red_1_Anim" },
  { tileSet: LILLYPAD_RED_2_ANIM, name: "Lillypad_Red_2_Anim" },
  { tileSet: LILLYPAD_RED_3_ANIM, name: "Lillypad_Red_3_Anim" },
  { tileSet: LILLYPAD_RED_4_ANIM, name: "Lillypad_Red_4_Anim" },
  { tileSet: LILLYPAD_RED_5_ANIM, name: "Lillypad_Red_5_Anim" },
  { tileSet: LILLYPAD_RED_6_ANIM, name: "Lillypad_Red_6_Anim" },
  { tileSet: WATER_GRASS_1_ANIM, name: "Water_Grass_1_Anim" },
  { tileSet: WATER_GRASS_2_ANIM, name: "Water_Grass_2_Anim" },
  { tileSet: ROCK_10_WATER_ANIM, name: "Rock_10_Water_Anim" },
  { tileSet: ROCK_15_WATER_ANIM, name: "Rock_15_Water_Anim" },
  { tileSet: ROCK_16_WATER_ANIM, name: "Rock_16_Water_Anim" },
  { tileSet: ROCK_3_WATER_ANIM, name: "Rock_3_Water_Anim" },
  { tileSet: ROCK_4_WATER_ANIM, name: "Rock_4_Water_Anim" },
  { tileSet: ROCK_5_WATER_ANIM, name: "Rock_5_Water_Anim" },
  { tileSet: ROCK_6_WATER_ANIM, name: "Rock_6_Water_Anim" },
  { tileSet: ROCK_7_WATER_ANIM, name: "Rock_7_Water_Anim" },
  { tileSet: ROCK_8_WATER_ANIM, name: "Rock_8_Water_Anim" },
  { tileSet: ROCK_9_WATER_ANIM, name: "Rock_9_Water_Anim" },
  { tileSet: PICNIC_BASKET, name: "Picnic_Basket" },
  { tileSet: SCARECROWS, name: "Scarecrows" },
  { tileSet: SIGNS, name: "Signs" },
  { tileSet: STONE_FENCE_BIG, name: "Stone_Fence_Big" },
  { tileSet: STONE_FENCE_SMALL, name: "Stone_Fence_Small" },
  { tileSet: WATER_TROUGHS, name: "Water_Troughs" },
  { tileSet: WELL, name: "Well" },
  { tileSet: WHITE_FENCE, name: "White_Fence" },
  { tileSet: PANTS_BLUE_ATTACK, name: "Pants_Blue_Attack" },
  { tileSet: PANTS_BLUE_AXE, name: "Pants_Blue_Axe" },
  { tileSet: PANTS_BLUE_BOW, name: "Pants_Blue_Bow" },
  { tileSet: PANTS_BLUE_CLIMB, name: "Pants_Blue_Climb" },
  { tileSet: PANTS_BLUE_DEATH, name: "Pants_Blue_Death" },
  { tileSet: PANTS_BLUE_FISHING, name: "Pants_Blue_Fishing" },
  { tileSet: PANTS_BLUE_HOE, name: "Pants_Blue_Hoe" },
  { tileSet: PANTS_BLUE_HORSE, name: "Pants_Blue_Horse" },
  { tileSet: PANTS_BLUE_IDLE, name: "Pants_Blue_Idle" },
  { tileSet: PANTS_BLUE_JUMP, name: "Pants_Blue_Jump" },
  { tileSet: PANTS_BLUE_PICKAXE, name: "Pants_Blue_Pickaxe" },
  { tileSet: PANTS_BLUE_PUSH, name: "Pants_Blue_Push" },
  { tileSet: PANTS_BLUE_ROLL, name: "Pants_Blue_Roll" },
  { tileSet: PANTS_BLUE_RUNNING, name: "Pants_Blue_Running" },
  { tileSet: PANTS_BLUE_WATERINGCAN, name: "Pants_Blue_WateringCan" },
  { tileSet: SHIRT_GREEN_ATTACK, name: "Shirt_Green_Attack" },
  { tileSet: SHIRT_GREEN_AXE, name: "Shirt_Green_Axe" },
  { tileSet: SHIRT_GREEN_BOW, name: "Shirt_Green_Bow" },
  { tileSet: SHIRT_GREEN_CLIMB, name: "Shirt_Green_Climb" },
  { tileSet: SHIRT_GREEN_DEATH, name: "Shirt_Green_Death" },
  { tileSet: SHIRT_GREEN_FISHING, name: "Shirt_Green_Fishing" },
  { tileSet: SHIRT_GREEN_HOE, name: "Shirt_Green_Hoe" },
  { tileSet: SHIRT_GREEN_HORSE, name: "Shirt_Green_Horse" },
  { tileSet: SHIRT_GREEN_IDLE, name: "Shirt_Green_Idle" },
  { tileSet: SHIRT_GREEN_JUMP, name: "Shirt_Green_Jump" },
  { tileSet: SHIRT_GREEN_PICKAXE, name: "Shirt_Green_Pickaxe" },
  { tileSet: SHIRT_GREEN_PUSH, name: "Shirt_Green_Push" },
  { tileSet: SHIRT_GREEN_ROLL, name: "Shirt_Green_Roll" },
  { tileSet: SHIRT_GREEN_RUNNING, name: "Shirt_Green_Running" },
  { tileSet: SHIRT_GREEN_WATERINGCAN, name: "Shirt_Green_WateringCan" },
  { tileSet: SHOES_BROWN_ATTACK, name: "Shoes_Brown_Attack" },
  { tileSet: SHOES_BROWN_AXE, name: "Shoes_Brown_Axe" },
  { tileSet: SHOES_BROWN_BOW, name: "Shoes_Brown_Bow" },
  { tileSet: SHOES_BROWN_CLIMB, name: "Shoes_Brown_Climb" },
  { tileSet: SHOES_BROWN_DEATH, name: "Shoes_Brown_Death" },
  { tileSet: SHOES_BROWN_FISHING, name: "Shoes_Brown_Fishing" },
  { tileSet: SHOES_BROWN_HOE, name: "Shoes_Brown_Hoe" },
  { tileSet: SHOES_BROWN_HORSE, name: "Shoes_Brown_Horse" },
  { tileSet: SHOES_BROWN_IDLE, name: "Shoes_Brown_Idle" },
  { tileSet: SHOES_BROWN_JUMP, name: "Shoes_Brown_Jump" },
  { tileSet: SHOES_BROWN_PICKAXE, name: "Shoes_Brown_Pickaxe" },
  { tileSet: SHOES_BROWN_PUSH, name: "Shoes_Brown_Push" },
  { tileSet: SHOES_BROWN_ROLL, name: "Shoes_Brown_Roll" },
  { tileSet: SHOES_BROWN_RUNNING, name: "Shoes_Brown_Running" },
  { tileSet: SHOES_BROWN_WATERINGCAN, name: "Shoes_Brown_WateringCan" },
  { tileSet: MEDIUM_HAIR_BROWN_ATTACK, name: "Medium_Hair_Brown_Attack" },
  { tileSet: MEDIUM_HAIR_BROWN_AXE, name: "Medium_Hair_Brown_Axe" },
  { tileSet: MEDIUM_HAIR_BROWN_BOW, name: "Medium_Hair_Brown_Bow" },
  { tileSet: MEDIUM_HAIR_BROWN_CLIMB, name: "Medium_Hair_Brown_Climb" },
  { tileSet: MEDIUM_HAIR_BROWN_DEATH, name: "Medium_Hair_Brown_Death" },
  { tileSet: MEDIUM_HAIR_BROWN_FISHING, name: "Medium_Hair_Brown_Fishing" },
  { tileSet: MEDIUM_HAIR_BROWN_HOE, name: "Medium_Hair_Brown_Hoe" },
  { tileSet: MEDIUM_HAIR_BROWN_HORSE, name: "Medium_Hair_Brown_Horse" },
  { tileSet: MEDIUM_HAIR_BROWN_IDLE, name: "Medium_Hair_Brown_Idle" },
  { tileSet: MEDIUM_HAIR_BROWN_JUMP, name: "Medium_Hair_Brown_Jump" },
  { tileSet: MEDIUM_HAIR_BROWN_PICKAXE, name: "Medium_Hair_Brown_Pickaxe" },
  { tileSet: MEDIUM_HAIR_BROWN_PUSH, name: "Medium_Hair_Brown_Push" },
  { tileSet: MEDIUM_HAIR_BROWN_ROLL, name: "Medium_Hair_Brown_Roll" },
  { tileSet: MEDIUM_HAIR_BROWN_RUNNING, name: "Medium_Hair_Brown_Running" },
  { tileSet: MEDIUM_HAIR_BROWN_WATERINGCAN, name: "Medium_Hair_Brown_WateringCan" },
  { tileSet: HANDS_BARE_ATTACK, name: "Hands_Bare_Attack" },
  { tileSet: HANDS_BARE_AXE, name: "Hands_Bare_Axe" },
  { tileSet: HANDS_BARE_BOW, name: "Hands_Bare_Bow" },
  { tileSet: HANDS_BARE_CLIMB, name: "Hands_Bare_Climb" },
  { tileSet: HANDS_BARE_DEATH, name: "Hands_Bare_Death" },
  { tileSet: HANDS_BARE_FISHING, name: "Hands_Bare_Fishing" },
  { tileSet: HANDS_BARE_HOE, name: "Hands_Bare_Hoe" },
  { tileSet: HANDS_BARE_HOLDING_IDLE, name: "Hands_Bare_Holding_Idle" },
  { tileSet: HANDS_BARE_HOLDING_RUNNING, name: "Hands_Bare_Holding_Running" },
  { tileSet: HANDS_BARE_HORSE, name: "Hands_Bare_Horse" },
  { tileSet: HANDS_BARE_IDLE, name: "Hands_Bare_Idle" },
  { tileSet: HANDS_BARE_JUMP, name: "Hands_Bare_Jump" },
  { tileSet: HANDS_BARE_LANTERN_IDLE, name: "Hands_Bare_Lantern_Idle" },
  { tileSet: HANDS_BARE_LANTERN_RUNNING, name: "Hands_Bare_Lantern_Running" },
  { tileSet: HANDS_BARE_PICKAXE, name: "Hands_Bare_Pickaxe" },
  { tileSet: HANDS_BARE_PUSH, name: "Hands_Bare_Push" },
  { tileSet: HANDS_BARE_ROLL, name: "Hands_Bare_Roll" },
  { tileSet: HANDS_BARE_RUNNING, name: "Hands_Bare_Running" },
  { tileSet: HANDS_BARE_TORCH_IDLE, name: "Hands_Bare_Torch_Idle" },
  { tileSet: HANDS_BARE_TORCH_RUNNING, name: "Hands_Bare_Torch_Running" },
  { tileSet: HANDS_BARE_WATERINGCAN, name: "Hands_Bare_WateringCan" },
  { tileSet: PLAYER_BASE_ATTACK, name: "Player_Base_Attack" },
  { tileSet: PLAYER_BASE_AXE, name: "Player_Base_Axe" },
  { tileSet: PLAYER_BASE_BOW, name: "Player_Base_Bow" },
  { tileSet: PLAYER_BASE_CLIMB, name: "Player_Base_Climb" },
  { tileSet: PLAYER_BASE_DEATH, name: "Player_Base_Death" },
  { tileSet: PLAYER_BASE_FISHING, name: "Player_Base_Fishing" },
  { tileSet: PLAYER_BASE_HOE, name: "Player_Base_Hoe" },
  { tileSet: PLAYER_BASE_HORSE, name: "Player_Base_Horse" },
  { tileSet: PLAYER_BASE_IDLE, name: "Player_Base_Idle" },
  { tileSet: PLAYER_BASE_JUMP, name: "Player_Base_Jump" },
  { tileSet: PLAYER_BASE_PICKAXE, name: "Player_Base_Pickaxe" },
  { tileSet: PLAYER_BASE_PUSH, name: "Player_Base_Push" },
  { tileSet: PLAYER_BASE_ROLL, name: "Player_Base_Roll" },
  { tileSet: PLAYER_BASE_RUNNING, name: "Player_Base_Running" },
  { tileSet: PLAYER_BASE_WATERINGCAN, name: "Player_Base_WateringCan" },
  { tileSet: WOODEN_BOW, name: "Wooden_Bow" },
  { tileSet: IRON_AXE, name: "Iron_Axe" },
  { tileSet: IRON_HOE, name: "Iron_Hoe" },
  { tileSet: IRON_PICKAXE, name: "Iron_Pickaxe" },
  { tileSet: IRON_SWORD, name: "Iron_Sword" },
  { tileSet: IRON_WATERINGCAN, name: "Iron_WateringCan" },
  { tileSet: LANTERN_IDLE, name: "Lantern_Idle" },
  { tileSet: LANTERN_RUNNING, name: "Lantern_Running" },
  { tileSet: TORCH_IDLE, name: "Torch_Idle" },
  { tileSet: TORCH_RUNNING, name: "Torch_Running" },
  { tileSet: WOODEN_FISHINGROD, name: "Wooden_FishingRod" },
  { tileSet: BEACH_DECOR_TILES, name: "Beach_Decor_Tiles" },
  { tileSet: BEACH_TILES, name: "Beach_Tiles" },
  { tileSet: BRIDGE_STONE_HORIZONTAL, name: "Bridge_Stone_Horizontal" },
  { tileSet: BRIDGE_STONE_VERTICAL, name: "Bridge_Stone_Vertical" },
  { tileSet: BRIDGE_WOOD, name: "Bridge_Wood" },
  { tileSet: CAVE_DOOR, name: "Cave_Door" },
  { tileSet: CAVE_DOORWAY_1, name: "Cave_Doorway_1" },
  { tileSet: CAVE_FLOOR, name: "Cave_Floor" },
  { tileSet: CAVE_FLOOR_1, name: "Cave_Floor_1" },
  { tileSet: CAVE_FLOOR_2, name: "Cave_Floor_2" },
  { tileSet: CAVE_FLOOR_DECORATION, name: "Cave_Floor_Decoration" },
  { tileSet: CAVE_FLOOR_LADDER, name: "Cave_Floor_Ladder" },
  { tileSet: CAVE_FLOOR_MIDDLE, name: "Cave_Floor_Middle" },
  { tileSet: CAVE_SUPPORT_1, name: "Cave_Support_1" },
  { tileSet: CAVE_SUPPORT_2, name: "Cave_Support_2" },
  { tileSet: CAVE_WALLS, name: "Cave_Walls" },
  { tileSet: CAVE_WALL_SUPPORT, name: "Cave_Wall_Support" },
  { tileSet: CAVE_WATER, name: "Cave_Water" },
  { tileSet: CAVE_WATER_ANIMATION, name: "Cave_Water_Animation" },
  { tileSet: RAILS, name: "Rails" },
  { tileSet: CAVE_ENTRANCE, name: "Cave_Entrance" },
  { tileSet: STONE_CLIFF_1_CAVE_ENTRANCE, name: "Stone_Cliff_1_Cave_Entrance" },
  { tileSet: STONE_CLIFF_1_TILE, name: "Stone_Cliff_1_Tile" },
  { tileSet: STONE_CLIFF_2_CAVE_ENTRANCE, name: "Stone_Cliff_2_Cave_Entrance" },
  { tileSet: STONE_CLIFF_2_TILE, name: "Stone_Cliff_2_Tile" },
  { tileSet: STONE_CLIFF_3_CAVE_ENTRANCE, name: "Stone_Cliff_3_Cave_Entrance" },
  { tileSet: STONE_CLIFF_3_TILE, name: "Stone_Cliff_3_Tile" },
  { tileSet: STONE_CLIFF_4_CAVE_ENTRANCE, name: "Stone_Cliff_4_Cave_Entrance" },
  { tileSet: STONE_CLIFF_4_TILE, name: "Stone_Cliff_4_Tile" },
  { tileSet: COBBLE_ROAD_1, name: "Cobble_Road_1" },
  { tileSet: COBBLE_ROAD_2, name: "Cobble_Road_2" },
  { tileSet: FARMLAND_TILE, name: "FarmLand_Tile" },
  { tileSet: FARMLAND_WET_TILE, name: "FarmLand_Wet_Tile" },
  { tileSet: GRASS_1_MIDDLE, name: "Grass_1_Middle" },
  { tileSet: GRASS_2_MIDDLE, name: "Grass_2_Middle" },
  { tileSet: GRASS_3_MIDDLE, name: "Grass_3_Middle" },
  { tileSet: GRASS_4_MIDDLE, name: "Grass_4_Middle" },
  { tileSet: GRASS_TILES_1, name: "Grass_Tiles_1" },
  { tileSet: GRASS_TILES_1_BLOB_TEST, name: "Grass_Tiles_1_Blob_TEST" },
  { tileSet: GRASS_TILES_1_BLOB_TEST_1, name: "Grass_Tiles_1_Blob_TEST_1" },
  { tileSet: GRASS_TILES_2, name: "Grass_Tiles_2" },
  { tileSet: GRASS_TILES_3, name: "Grass_Tiles_3" },
  { tileSet: GRASS_TILES_4, name: "Grass_Tiles_4" },
  { tileSet: PATH_DECORATION, name: "Path_Decoration" },
  { tileSet: PATH_MIDDLE, name: "Path_Middle" },
  { tileSet: PICNIC_BLANKETS, name: "Picnic_Blankets" },
  { tileSet: FISH_ANIMATED_TILE, name: "Fish_Animated_Tile" },
  { tileSet: WATER_DECORATION, name: "Water_Decoration" },
  { tileSet: WATER_FOAM_ANIMATION, name: "Water_Foam_Animation" },
  { tileSet: WATER_MIDDLE, name: "Water_Middle" },
  { tileSet: WATER_MIDDLE_ANIM_1, name: "Water_Middle_Anim_1" },
  { tileSet: WATER_MIDDLE_ANIM_2, name: "Water_Middle_Anim_2" },
  { tileSet: WATER_STONE_TILE_1, name: "Water_Stone_Tile_1" },
  { tileSet: WATER_STONE_TILE_1_ANIM, name: "Water_Stone_Tile_1_Anim" },
  { tileSet: WATER_STONE_TILE_2, name: "Water_Stone_Tile_2" },
  { tileSet: WATER_STONE_TILE_2_ANIM, name: "Water_Stone_Tile_2_Anim" },
  { tileSet: WATER_STONE_TILE_3, name: "Water_Stone_Tile_3" },
  { tileSet: WATER_STONE_TILE_3_ANIM, name: "Water_Stone_Tile_3_Anim" },
  { tileSet: WATER_STONE_TILE_4, name: "Water_Stone_Tile_4" },
  { tileSet: WATER_STONE_TILE_4_ANIM, name: "Water_Stone_Tile_4_Anim" },
  { tileSet: WATER_TILE_1, name: "Water_Tile_1" },
  { tileSet: WATER_TILE_1_ANIM, name: "Water_Tile_1_Anim" },
  { tileSet: WATER_TILE_2, name: "Water_Tile_2" },
  { tileSet: WATER_TILE_2_ANIM, name: "Water_Tile_2_Anim" },
  { tileSet: WATER_TILE_3, name: "Water_Tile_3" },
  { tileSet: WATER_TILE_3_ANIM, name: "Water_Tile_3_Anim" },
  { tileSet: WATER_TILE_4, name: "Water_Tile_4" },
  { tileSet: WATER_TILE_4_ANIM, name: "Water_Tile_4_Anim" },
  { tileSet: WATERFALL_1, name: "Waterfall_1" },
  { tileSet: WATERFALL_2, name: "Waterfall_2" },
  { tileSet: WATERFALL_3, name: "Waterfall_3" },
  { tileSet: WATERFALL_4, name: "Waterfall_4" },
  { tileSet: WATERFALL_5, name: "Waterfall_5" },
  { tileSet: WATERFALL_6, name: "Waterfall_6" },
  { tileSet: WATERFALL_7, name: "Waterfall_7" },
  { tileSet: WATERFALL_8, name: "Waterfall_8" },
  { tileSet: BIG_BIRCH_TREE, name: "Big_Birch_Tree" },
  { tileSet: BIG_FRUIT_TREE, name: "Big_Fruit_Tree" },
  { tileSet: BIG_OAK_TREE, name: "Big_Oak_Tree" },
  { tileSet: BIG_SPRUCE_TREE, name: "Big_Spruce_tree" },
  { tileSet: BIRCH_LEAF_PARTICLE, name: "Birch_Leaf_Particle" },
  { tileSet: MEDIUM_BIRCH_TREE, name: "Medium_Birch_Tree" },
  { tileSet: MEDIUM_FRUIT_TREE, name: "Medium_Fruit_Tree" },
  { tileSet: MEDIUM_OAK_TREE, name: "Medium_Oak_Tree" },
  { tileSet: MEDIUM_SPRUCE_TREE, name: "Medium_Spruce_Tree" },
  { tileSet: OAK_LEAF_PARTICLE, name: "Oak_Leaf_Particle" },
  { tileSet: SMALL_BIRCH_TREE, name: "Small_Birch_Tree" },
  { tileSet: SMALL_FRUIT_TREE, name: "Small_Fruit_Tree" },
  { tileSet: SMALL_OAK_TREE, name: "Small_Oak_Tree" },
  { tileSet: SMALL_SPRUCE_TREE, name: "Small_Spruce_Tree" },
  { tileSet: SPRUCE_NEEDLE_PARTICLE, name: "Spruce_Needle_Particle" },
  { tileSet: CLOUDS, name: "Clouds" },
  { tileSet: RAIN_DROP, name: "Rain_Drop" },
  { tileSet: RAIN_DROP_IMPACT, name: "Rain_Drop_Impact" },
  { tileSet: WIND_ANIM, name: "Wind_Anim" },
];
